// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarcraftdleAPI.Domain.Enums;
using WarcraftdleAPI.Infrastructure;

#nullable disable

namespace WarcraftdleAPI.Infrastructure.Migrations
{
    [DbContext(typeof(WarcraftdleDbContext))]
    [Migration("20240527204914_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AffiliationCharacter", b =>
                {
                    b.Property<int>("AffiliationsId")
                        .HasColumnType("integer");

                    b.Property<int>("CharactersId")
                        .HasColumnType("integer");

                    b.HasKey("AffiliationsId", "CharactersId");

                    b.HasIndex("CharactersId");

                    b.ToTable("AffiliationCharacter");
                });

            modelBuilder.Entity("CharacterZone", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("integer");

                    b.Property<int>("ZonesId")
                        .HasColumnType("integer");

                    b.HasKey("CharactersId", "ZonesId");

                    b.HasIndex("ZonesId");

                    b.ToTable("CharacterZone");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.Entities.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Affiliation");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<Expansion[]>("Expansions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Race")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("AffiliationCharacter", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.Entities.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterZone", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
