// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarcraftdleAPI.Infrastructure;

#nullable disable

namespace WarcraftdleAPI.Infrastructure.Migrations.WowCharactersDb
{
    [DbContext(typeof(WowCharactersDbContext))]
    [Migration("20231214213506_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AffiliationWowCharacter", b =>
                {
                    b.Property<int>("AffiliationsId")
                        .HasColumnType("int");

                    b.Property<int>("WowCharactersId")
                        .HasColumnType("int");

                    b.HasKey("AffiliationsId", "WowCharactersId");

                    b.HasIndex("WowCharactersId");

                    b.ToTable("AffiliationWowCharacter");
                });

            modelBuilder.Entity("ExpansionWowCharacter", b =>
                {
                    b.Property<int>("ExpansionsId")
                        .HasColumnType("int");

                    b.Property<int>("WowCharactersId")
                        .HasColumnType("int");

                    b.HasKey("ExpansionsId", "WowCharactersId");

                    b.HasIndex("WowCharactersId");

                    b.ToTable("ExpansionWowCharacter");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Affiliation");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Priest"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shaman"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Demon Hunter"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Death Knight"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Evoker"
                        });
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expansion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TBC",
                            Name = "The Burning Crusade"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "WotLK",
                            Name = "Wrath of the Lich King"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "Cata",
                            Name = "Cataclysm"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "MOP",
                            Name = "Mists of Pandaria"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "WOD",
                            Name = "Warlords of Draenor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legion"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "BFA",
                            Name = "Battle for Azeroth"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "SL",
                            Name = "Shadowlands"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "DF",
                            Name = "Dragonflight"
                        });
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Night Elf"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gnome"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Draenei"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Worgen"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pandaren"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Undead"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tauren"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Blood Elf"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dragon"
                        });
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.WowCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GenderId");

                    b.HasIndex("RaceId");

                    b.ToTable("WowCharacter");
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("WowCharacterZone", b =>
                {
                    b.Property<int>("WowCharactersId")
                        .HasColumnType("int");

                    b.Property<int>("ZonesId")
                        .HasColumnType("int");

                    b.HasKey("WowCharactersId", "ZonesId");

                    b.HasIndex("ZonesId");

                    b.ToTable("WowCharacterZone");
                });

            modelBuilder.Entity("AffiliationWowCharacter", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.WowCharacter", null)
                        .WithMany()
                        .HasForeignKey("WowCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExpansionWowCharacter", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Expansion", null)
                        .WithMany()
                        .HasForeignKey("ExpansionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.WowCharacter", null)
                        .WithMany()
                        .HasForeignKey("WowCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarcraftdleAPI.Domain.WowCharacter.WowCharacter", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Gender");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("WowCharacterZone", b =>
                {
                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.WowCharacter", null)
                        .WithMany()
                        .HasForeignKey("WowCharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarcraftdleAPI.Domain.WowCharacter.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZonesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
