name: Run tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore ./WarcraftdleAPI

    - name: Build
      run: dotnet build --no-restore ./WarcraftdleAPI

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./WarcraftdleAPI
